# Generated by Django 5.2.8 on 2025-11-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_transaction_recipient_email_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='recipient_bank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
